#!/usr/bin/env python3
"""
Generate .streamlit/secrets.toml untuk Streamlit Authenticator (best practice).
- Hash bcrypt via streamlit_authenticator.utilities.Hasher (context7: mkhorasani/streamlit-authenticator)
- Cookie key random 64 hex jika kosong
- 1 akun saja, expiry 1 hari (sinkron jadwal tanggal 4)
- Idempotent, tidak log password plaintext, file 600

Usage:
  AUTH_USERNAME=admin AUTH_PASSWORD='MyS3cret!' python scripts/generate_auth_secrets.py
  # atau isi .env lalu: python scripts/generate_auth_secrets.py
  # atau: python scripts/generate_auth_secrets.py --username admin --password 'xxx' --email admin@pendidikan.karangasemkab.go.id
"""
import argparse
import os
import secrets
import sys
from pathlib import Path

# Load .env jika ada
try:
    from dotenv import load_dotenv

    load_dotenv()
except Exception:
    pass

try:
    from streamlit_authenticator.utilities.hasher import Hasher
except ImportError as e:
    print(f"ERROR: streamlit-authenticator belum terinstall: {e}", file=sys.stderr)
    print("  pip install -r requirements.txt", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
STREAMLIT_DIR = ROOT / ".streamlit"
SECRETS_PATH = STREAMLIT_DIR / "secrets.toml"
EXAMPLE_PATH = STREAMLIT_DIR / "secrets.toml.example"

DEFAULT_EMAIL = "admin@pendidikan.karangasemkab.go.id"
DEFAULT_USERNAME = "admin"
DEFAULT_COOKIE_NAME = "karangasem_auth"
DEFAULT_EXPIRY = "1"


def generate_cookie_key() -> str:
    return secrets.token_hex(32)  # 64 chars


def build_secrets_toml(username: str, name: str, email: str, hashed_pw: str, cookie_name: str, cookie_key: str, expiry: str) -> str:
    # TOML inline — password hash mengandung $ dan ., perlu dikutip
    return f"""# Streamlit secrets — JANGAN commit file ini (gitignore)
# Generated by scripts/generate_auth_secrets.py — best practice: bcrypt + cookie terenkripsi
# Cookie expiry 1 hari sinkron jadwal penarikan tanggal 4

[auth]
cookie_name = "{cookie_name}"
cookie_key = "{cookie_key}"
cookie_expiry_days = {expiry}

[credentials]
[credentials.usernames.{username}]
name = "{name}"
email = "{email}"
password = "{hashed_pw}"
"""


def main():
    parser = argparse.ArgumentParser(description="Generate .streamlit/secrets.toml")
    parser.add_argument("--username", default=os.getenv("AUTH_USERNAME", DEFAULT_USERNAME))
    parser.add_argument("--password", default=os.getenv("AUTH_PASSWORD", ""))
    parser.add_argument("--email", default=os.getenv("AUTH_EMAIL", DEFAULT_EMAIL))
    parser.add_argument("--name", default=os.getenv("AUTH_NAME", "Admin Karangasem"))
    parser.add_argument("--cookie-name", default=os.getenv("AUTH_COOKIE_NAME", DEFAULT_COOKIE_NAME))
    parser.add_argument("--cookie-key", default=os.getenv("AUTH_COOKIE_KEY", ""))
    parser.add_argument("--expiry", default=os.getenv("AUTH_COOKIE_EXPIRY_DAYS", DEFAULT_EXPIRY))
    parser.add_argument("--force", action="store_true", help="Overwrite existing secrets.toml")
    args = parser.parse_args()

    username = args.username.strip()
    password = args.password  # jangan strip spasi di dalam?
    email = args.email.strip()
    name = args.name.strip()
    cookie_name = args.cookie_name.strip()
    cookie_key = args.cookie_key.strip()
    expiry = args.expiry.strip()

    if not username:
        print("ERROR: username kosong (AUTH_USERNAME)", file=sys.stderr)
        sys.exit(1)
    if not password:
        # Coba interactive prompt jika TTY
        if sys.stdin.isatty():
            import getpass

            password = getpass.getpass(f"Password untuk '{username}' (input tersembunyi): ").strip()
        if not password:
            print("ERROR: AUTH_PASSWORD kosong. Isi .env atau --password", file=sys.stderr)
            sys.exit(1)

    if not cookie_key:
        cookie_key = generate_cookie_key()
        print(f"[info] AUTH_COOKIE_KEY kosong → generate random 64 hex")

    # Hash via Hasher (bcrypt $2b$12)
    hashed = Hasher.hash(password)
    # Verify
    if not Hasher.check_pw(password, hashed):
        print("ERROR: verifikasi hash gagal", file=sys.stderr)
        sys.exit(1)

    # Validasi expiry numeric
    try:
        float(expiry)
    except ValueError:
        print(f"ERROR: expiry bukan angka: {expiry}", file=sys.stderr)
        sys.exit(1)

    STREAMLIT_DIR.mkdir(parents=True, exist_ok=True)

    if SECRETS_PATH.exists() and not args.force:
        print(f"WARNING: {SECRETS_PATH} sudah ada. Gunakan --force untuk overwrite.", file=sys.stderr)
        print(f"  Akan buat {SECRETS_PATH}.new untuk review", file=sys.stderr)
        target = SECRETS_PATH.with_suffix(".toml.new")
    else:
        target = SECRETS_PATH

    content = build_secrets_toml(username, name, email, hashed, cookie_name, cookie_key, expiry)
    target.write_text(content, encoding="utf-8")
    # 600
    try:
        target.chmod(0o600)
    except Exception:
        pass

    print(f"[ok] Written {target} (600)")
    print(f"  username: {username}")
    print(f"  email: {email}")
    print(f"  cookie: {cookie_name} expiry {expiry} hari")
    print(f"  hash: {hashed[:12]}... (bcrypt)")
    if target != SECRETS_PATH:
        print(f"  Review lalu: mv {target} {SECRETS_PATH}")
    # Jangan print password / cookie_key penuh ke log (scrub sudah)
    # Info next step
    print(f"\nNext: sudo docker compose up -d --build  # atau docker compose up -d --build jika sudah group docker")
    print(f"  Cek: sudo docker logs backbone-v3 --tail 20 && sudo docker ps")


if __name__ == "__main__":
    main()
